function(EXPECT)
    if(${ARGN})
        message("[OK]   ${ARGN}")
    else()
        message(FATAL_ERROR "[FAIL] ${ARGN}")
    endif()
endfunction()

message("Runing test suite...")
include(Test/Bits/String)
# include(Test/Structure)
# include(Test/Package)